import org.springframework.boot.gradle.tasks.bundling.BootBuildImage

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    alias(libs.plugins.spring.boot)
}
apply(plugin = "io.spring.dependency-management")

repositories {
    mavenCentral()
    gradlePluginPortal()
}
group = "org.allengueco"
version = "1.0-SNAPSHOT"
java {
    sourceCompatibility = JavaVersion.VERSION_21
}

dependencies {
    implementation(project(":frontend"))
    implementation(libs.bundles.spring)
    implementation(libs.bundles.eclipse.collections)
    implementation(libs.bundles.jackson)
    runtimeOnly(libs.postgres)
    testImplementation(libs.spring.boot.starter.test)
    testImplementation(libs.bundles.testcontainers)
    testRuntimeOnly(libs.junit.platform.launcher)
}

description = "backend"

tasks {
    test {
        useJUnitPlatform()
    }
    withType<JavaCompile> {
        options.encoding = "UTF-8"
    }

    named<BootBuildImage>("bootBuildImage") {
//        imageName.set("agueco.registry.jetbrains.space/p/betaguess/betaguess/betaguess:${project.version}")
//        publish.set(true)
//
//        docker {
//            publishRegistry {
//                username.set(providers.environmentVariable("BETAGUESS_CLIENT_ID"))
//                password.set(providers.environmentVariable("BETAGUESS_CLIENT_SECRET"))
//            }
//        }
    }
}
